[project]
name = "calculator-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []


[tool.uv.sources]
agentic_environments = { workspace = true }

[tool.uv.workspace]
members = [
	"../../../agentic_environments"
]

